### ISSUE TITLE
Implement solve-to-pattern feature natively in C code

### ISSUE THREAD

**Issue by muodov** [muodov/kociemba#13]
This feature is implemented purely in Python for now, so it is not yet available for users of C library

**Comment by ansiwen** [comment]
I'm just working on this...

**Comment by muodov** [comment]
Awesome, it's so inspiring to see someone willing to help :) Thanks for your effort!

**Comment by muodov** [comment]
Resolved by https://github.com/muodov/kociemba/pull/19
