### ISSUE TITLE
Running with a solved cube

### ISSUE THREAD

**Issue by jegali** [muodov/kociemba#44]
When running the solver with a string for the solved cube, it returns this:

R L U2 R L' B2 U2 R2 F2 L2 D2 L2 F2

Why is that so? I would expect to print the solver "solved cube"

**Comment by muodov** [comment]
Hi @jegali , kociemba is the implementation of the Two-Phase algorithm, which doesn't check for special cases, it just gives you a technically possible solution. Detecting a solved cube is very straightforward, you can do it before calling the `solve()` function.
