### ISSUE TITLE
Feature request: Solve to pattern.

### ISSUE THREAD

**Issue by ansiwen** [muodov/kociemba#6]
Would be nice to also give a target pattern to solve it to. Should be easy, if I'm mistaken. Just solve from pattern to solved state, and apply the resulting maneuvers to the starting pattern and solve it from there. The resulting maneuvers should solve the cube to the pattern. Right?
Would be useful also to bring the cube into a given scrambled states, like only the last-layer scrambled for training purposes.

I might be able to implement it by myself during the holidays.

**Comment by muodov** [comment]
Sounds cool. Any help is appreciated!

**Comment by muodov** [comment]
Fixed in https://github.com/muodov/kociemba/pull/8
